vesta_si_erpnext/vesta_si_erpnext/doctype/inspection_report_parameter/inspection_report_parameter.json
vesta_si_erpnext/vesta_si_erpnext/doctype/inspection_report_parameter/inspection_report_parameter.py
vesta_si_erpnext/vesta_si_erpnext/doctype/quality_inspection_report_settings/quality_inspection_report_settings.js
vesta_si_erpnext/vesta_si_erpnext/doctype/quality_inspection_report_settings/quality_inspection_report_settings.json
vesta_si_erpnext/vesta_si_erpnext/doctype/quality_inspection_report_settings/quality_inspection_report_settings.py
vesta_si_erpnext/vesta_si_erpnext/doctype/quality_inspection_report_settings/test_quality_inspection_report_settings.py
vesta_si_erpnext/vesta_si_erpnext/report/batch_wise_balance_and_inspection/batch_wise_balance_and_inspection.js
vesta_si_erpnext/vesta_si_erpnext/report/batch_wise_balance_and_inspection/batch_wise_balance_and_inspection.json
vesta_si_erpnext/vesta_si_erpnext/report/batch_wise_balance_and_inspection/batch_wise_balance_and_inspection.py

Report Includes:
- Item
- Warehouse
- Batch
- Balance
- UOM
- Quality Inspection (ID)- So when they enter some numbers in Iron, Calcium or Aluminium then all the QI which has those numbers should be visible with their IDs
- Iron Content
- Calcium Content
- Aluminium Content
- Supplier bag no
Filters:
- QI
- Iron, Calcium, Aluminium
- Supplier Bag No.

feat: report for batch-wise balance and inspection

---

vesta_si_erpnext/public/js/quality_inspection.js
vesta_si_erpnext/public/js/stock_entry.js
vesta_si_erpnext/vesta_si_erpnext/report/batch_wise_balance_and_inspection/batch_wise_balance_and_inspection.py
vesta_si_erpnext/vesta_si_erpnext/stock_entry.py

Check support ticket https://frappe.io/app/issue/ISS-22-23-00148

fix: multiple issues related to quality inspection

---

vesta_si_erpnext/vesta_si_erpnext/quality_inspection.py

Fixed issue https://frappe.io/app/issue/ISS-22-23-00808

fix: Non numeric field not found

---

vesta_si_erpnext/vesta_si_erpnext/doctype/analytical_certificate_drum/analytical_certificate_drum.json

feat: mapped new inspection parameters

---

vesta_si_erpnext/vesta_si_erpnext/report/purchase___vat_breakup/purchase___vat_breakup.js
vesta_si_erpnext/vesta_si_erpnext/report/purchase___vat_breakup/purchase___vat_breakup.json
vesta_si_erpnext/vesta_si_erpnext/report/purchase___vat_breakup/purchase___vat_breakup.py
vesta_si_erpnext/vesta_si_erpnext/report/sales___vat_breakup/sales___vat_breakup.js
vesta_si_erpnext/vesta_si_erpnext/report/sales___vat_breakup/sales___vat_breakup.json
vesta_si_erpnext/vesta_si_erpnext/report/sales___vat_breakup/sales___vat_breakup.py

Add Sales and Purchase VAT breakup reports as per the client specifications.

feat: Add sales and purchase VAT breakup reports

---

vesta_si_erpnext/hooks.py
vesta_si_erpnext/public/js/sales_invoice.js
vesta_si_erpnext/vesta_si_erpnext/doc_events/sales_invoice.py

Get Items from Stock Entry in Sales invoice

feat: Get Items from Stock Entry in Sales invoice

---

vesta_si_erpnext/hooks.py

fix:',' is missing in  hooks.py line no 40 , 39

fix:',' is missing in  hooks.py line no 40 , 39

---

vesta_si_erpnext/public/js/sales_invoice.js

fix:made changes to solve No module found error

fix:made changes to solve No module found error

---

vesta_si_erpnext/vesta_si_erpnext/page/payment_export/payment_export.js
vesta_si_erpnext/vesta_si_erpnext/page/payment_export/payment_export.py
vesta_si_erpnext/vesta_si_erpnext/page/payment_export/payment_export_table.html

Use supplier name instead of supplier id 
Remove hypen from Bank Giro number in Supplier 
Set 'Required Execution Date' to current date 
Link radiation with payment Entry Document

fix: Xml file creation changes 

---

vesta_si_erpnext/vesta_si_erpnext/report/monthly_sales_invoice_detail/monthly_sales_invoice_detail.js
vesta_si_erpnext/vesta_si_erpnext/report/monthly_sales_invoice_detail/monthly_sales_invoice_detail.py

added some columns in existing report

---

vesta_si_erpnext/vesta_si_erpnext/doc_events/payment_entry.py
vesta_si_erpnext/vesta_si_erpnext/doctype/payment_export_log/payment_export_log.json
vesta_si_erpnext/vesta_si_erpnext/doctype/payment_export_log/payment_export_log.py
vesta_si_erpnext/vesta_si_erpnext/doctype/payment_transaction_log/payment_transaction_log.json
vesta_si_erpnext/vesta_si_erpnext/page/payment_export/payment_export.py

Payment Export Log Changes

---

vesta_si_erpnext/vesta_si_erpnext/page/payment_run/payment_run.js
vesta_si_erpnext/vesta_si_erpnext/page/payment_run/payment_run.py
vesta_si_erpnext/vesta_si_erpnext/page/payment_run/purchase_invoice_table.html
vesta_si_erpnext/vesta_si_erpnext/report/purchase_invoice_timeline_report/purchase_invoice_timeline_report.py
vesta_si_erpnext/vesta_si_erpnext/report/unhappy_po_timeline_report/unhappy_po_timeline_report.py

Purchase Invoice Timeline Report
Unhappy PO Timeline Report

Report Changes : Column Processing Days in all report

---

vesta_si_erpnext/vesta_si_erpnext/doc_events/payment_entry.py
vesta_si_erpnext/vesta_si_erpnext/report/ap_analysis/ap_analysis.py
vesta_si_erpnext/vesta_si_erpnext/report/supplier_bank_detail_tracking_report/supplier_bank_detail_tracking_report.js
vesta_si_erpnext/vesta_si_erpnext/report/supplier_bank_detail_tracking_report/supplier_bank_detail_tracking_report.json
vesta_si_erpnext/vesta_si_erpnext/report/supplier_bank_detail_tracking_report/supplier_bank_detail_tracking_report.py
vesta_si_erpnext/vesta_si_erpnext/report/unhappy_po_timeline_report/unhappy_po_timeline_report.py

Mapping of the data from another report 
and calculating average of processing days

New Report : Supplier Bank Detail Tracking Report

---

vesta_si_erpnext/vesta_si_erpnext/page/payment_export/cross_border_payment.py
vesta_si_erpnext/vesta_si_erpnext/report/ap_analysis/ap_analysis.js
vesta_si_erpnext/vesta_si_erpnext/report/ap_analysis/ap_analysis.py
vesta_si_erpnext/vesta_si_erpnext/report/unhappy_po_timeline_report/unhappy_po_timeline_report.py

Added a Data From Purchase Receipt and version of purchase receipt
Column : Purchase Receipt, Created by , Created ON, Submited By , Submitted ON
Comment line has been removed from Cross Border XML Code

Changes of AP Analysis Report

---

vesta_si_erpnext/hooks.py
vesta_si_erpnext/vesta_si_erpnext/doc_events/supplier.py
vesta_si_erpnext/vesta_si_erpnext/doctype/payment_export_log/payment_export_log.js
vesta_si_erpnext/vesta_si_erpnext/doctype/payment_export_log/payment_export_log.json
vesta_si_erpnext/vesta_si_erpnext/doctype/payment_transaction_log/payment_transaction_log.json
vesta_si_erpnext/vesta_si_erpnext/page/payment_export/payment_export.py
vesta_si_erpnext/vesta_si_erpnext/report/ap_analysis/ap_analysis.py
vesta_si_erpnext/vesta_si_erpnext/report/detailed_asset_depreciations_and_balances/detailed_asset_depreciations_and_balances.py

IBAN Validation
Columns added to payment export log same as payment export screen also add same details in excel file
Not allow to submit payment entry is payment export log is at __unsaved position

Changes as mentioned in a PR Comment

---

vesta_si_erpnext/hooks.py
vesta_si_erpnext/overrides/account_controller.py
vesta_si_erpnext/public/js/utils.js

Update Item tax Issue , Fixed : tax update on new update item

---

vesta_si_erpnext/vesta_si_erpnext/doc_events/payment_entry.py
vesta_si_erpnext/vesta_si_erpnext/doc_events/purchase_invoice.py

Exclude purchase invoices in popup Supplier (SUPPLIER0504)

---

vesta_si_erpnext/vesta_si_erpnext/page/payment_export/payment_export.py
vesta_si_erpnext/vesta_si_erpnext/page/payment_run/payment_run.js
vesta_si_erpnext/vesta_si_erpnext/page/payment_run/payment_run.py

On payment run page Cross border invoices was not fetch properly 
For cross border Other , payment export log was fetching wrong currency symbol fixed that

Fixed the cross border other invoice fetch issue in payment run

---

vesta_si_erpnext/vesta_si_erpnext/doctype/payment_export_log/payment_export_log.js
vesta_si_erpnext/vesta_si_erpnext/doctype/payment_export_log/payment_export_log.json
vesta_si_erpnext/vesta_si_erpnext/doctype/payment_export_log/payment_export_log.py

Added a Conformation MSG

---

vesta_si_erpnext/vesta_si_erpnext/doc_events/payment_entry.py

if different amount between -1 and 1 then. --> roundoff account
if different amount < -1 or >1 then ---> exchange gain loss account

Auto selection of roundoff and exchange gain loss account fixed the issue
